package:
  name: tempo
  version: "0.1.1"

source:
  path: .

build:
  script:
    - mkdir -p $PREFIX/lib/mojo
    - cp -r tempo $PREFIX/lib/mojo/

requirements:
  host:
    - mojo ==1.0.0b1
  run:
    - mojo ==1.0.0b1

about:
  summary: Minimal Timestamp and Duration types for Mojo
  license: MIT
